version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=snippetbox
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
